server:
  port: 18080
spring:
  application:
    name: dahua-test-graph
  datasource:
    url: jdbc:postgresql://20.12.0.38:5432/prptdb
    username: schedulerdb
    #    password: cG9zdGdyZXN0ZXN0Cg==
    #   password: ENC(uVHRDvJL/EBn+YXdnDKaNETgT5sKrU4F)
    password: LC@tyzy2025!
    driver-class-name: org.postgresql.Driver

  ai:
    model:
      embedding: yc
    openai:
      base-url: http://20.200.25.216:8080
      api-key: b8d5ca9f6f344058ba9d8cad089ac53d97a7a3e6021242638069e67bb6b09881
      embedding:
        embeddingsPath: "/embeddings"
        enabled: true
        metadata-mode: EMBED
        options:
          model: Bge-m3-test
      chat:
        options:
          model: Qwen25-32B-1-test
          internal-tool-execution-enabled: false
          headers:
            Authorization: "Bearer b8d5ca9f6f344058ba9d8cad089ac53d97a7a3e6021242638069e67bb6b09881"
        completionsPath: /v1/chat/completion


yc:
  core:
    ai:
      url: http://20.200.175.85:32011/online-service/rag/v1/
      send-sys-no: 99370000000
      target-sys-no: 99370000000
      embedding:
        enabled: true
      vector:
        enabled: true
        collection-name: pdf_inner_rule_index
        vector-field-name: embedding
      rerank:
        enabled: true


rerank:
  enabled: false
  base-url: http://20.200.25.216:8080
  api-key: b8d5ca9f6f344058ba9d8cad089ac53d97a7a3e6021242638069e67bb6b09881
  rerankPath: "/rerank"
  model: Bge-rerank-v2-m3-test

jasypt:
  encryptor:
    password: Yld@123

logging:
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.dahuaboke.mpda.bot.tools.entity


